[package]
name = "nucleus_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.87"
bytes = "1.11.1"
chrono = "0.4.40"
clap = { version = "4.5.32", features = ["derive", "env"] }
nucleus = { path = "../nucleus", features = ["client", "debug"] }
tokio = { version = "1.38.0", features = [
    "rt-multi-thread",
    "rt",
    "macros",
    "net",
    "tracing",
    "io-util",
    "time",
    "io-std",
    "signal",
] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
